name: StudyBuddy Build & Test

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'StudyBuddy/**'
      - '*.sln'
  pull_request:
    paths:
      - 'StudyBuddy/**'
      - '*.sln'

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore
        run: dotnet restore ./StudyBuddy/

      - name: Build
        run: dotnet build -c Release --no-restore ./StudyBuddy/

      - name: Test StudyBuddy
        run: dotnet test ./Tests/StudyBuddyTests/